name: cook_book
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.0.2
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Add assets for images
  assets:
    - assets/images/img2.png
    - assets/images/img1.png
    - assets/images/breakfast.png
    - assets/images/lunch.png
    - assets/images/dinner.png
    - assets/images/dessert.png
    - assets/images/drink.png
  # Add custom fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 700
