name: cook_book
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  sqflite: ^2.2.0+4
  path: ^1.9.0
  sqflite_common_ffi: ^2.2.1
  sqflite_common_ffi_web: ^0.4.5+4

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets for images
  assets:
    - assets/images/img2.png
    - assets/images/img1.png
    - assets/images/breakfast.png
    - assets/images/lunch.png
    - assets/images/dinner.png
    - assets/images/dessert.png
    - assets/images/drink.png
    - assets/images/pancake.png
    - assets/images/alooparatha.png
    - assets/images/omlette.png
    - assets/images/french.png
    - assets/images/smoothie.png
    - assets/images/avocado.png
    - assets/images/nihari.png
    - assets/images/channa.png
    - assets/images/halwa.png
    - assets/images/naan.png
    - assets/images/GhulabJamun.png
    - assets/images/Tiramisu.png
    - assets/images/kheer.png
    - assets/images/cheesecake.png
    - assets/images/brownie.png
    - assets/images/shahitukray.png
    - assets/images/teacake.png
    - assets/images/macrons.png
    - assets/images/Trifle.png
    - assets/images/chocochip.png
    
  # Add custom fonts
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 700
